#!/bin/bash
printf "=========================================================================\n"
printf "                            Install Phalcon-1.3.4 Module for PHP\n"
printf "=========================================================================\n"

cd /opt
git clone git://github.com/phalcon/cphalcon.git
cd cphalcon/build
sudo ./install

cat > "/etc/php.d/phalcon.ini" << END
extension=phalcon.so
END

/etc/init.d/nginx restart
/etc/init.d/php-fpm restart

printf "Installation completed....\n\n"
printf "=========================================================================\n"
printf "Return to PINE AUTO menu\n"