#!/bin/bash
printf "=========================================================================\n"
printf "                            Install MongoDB Server\n"
printf "=========================================================================\n"

cat > "/etc/yum.repos.d/mongodb.repo" << END
[mongodb]
name=MongoDB Repository
baseurl=http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/
gpgcheck=0
enabled=1
END

yum install -y mongodb-org mongodb-org-server mongodb-org-mongos mongodb-org-shell mongodb-org-tools
/etc/init.d/mongod start
chkconfig mongod on

printf "Installation completed....\n\n"
printf "=========================================================================\n"
printf "Return to PINE AUTO menu\n"