#!/bin/bash
printf "=========================================================================\n"
printf "                            Install MySQL Server\n"
printf "=========================================================================\n"
echo "Process is starting....."

rpm -Uvh http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
yum install mysql-server -y
systemctl start mysqld
systemctl enable mysqld


printf "=========================================================================\n"
printf "                            Basic configuration for MySQL\n"
printf "=========================================================================\n"

mysql_secure_installation

printf "=========================================================================\n"
printf "Return to PINE AUTO menu\n"